### ISSUE TITLE
Case Studies lower priority

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#1]
We tried to get case studies a few years ago, and we not successful. I **do** think it is worth trying again; however, not spending energy on it yet.

I think it is a lower priority than many of the things on EOWG's work list, such as Easy Checks Next Gen and translations.

**Comment by sharronrush** [comment]
Actually we editors do not agree that this is low priority.In fact when you can show examples and tell stories about actual successful implementations, that is often more persuasive than any proselytizing can be.

**Comment by slhenry** [comment]
Agree that case studies can be very powerful.

Excited that Editors think they can get some persuasive ones. Would be good to represent range of geographic regions, types of organizations, etc.

Hope it doesn't delay other work. Likely not much given different people focusing on different things.

Happy to close this issue.

**Comment by slhenry** [comment]
I had another idea for if we have trouble getting strong Case Studies. Testimonials like.

W3C often gets "testimonials" to go along with Press Releases for new standards. For example: [ARIA testimonials](https://www.w3.org/2014/03/aria-testimonials.html.en).

Maybe we could get prominent organizations to say a few sentences about the business benefits of implementing web accessibility, even if they're not up for doing a full case study. Certainly that wouldn't be nearly as powerful as case studies, but might be of some help.

W3C typically sends a call for testimonials to all members and, afaik, uses all of them that get polished and agreed upon. So that takes care of vendor-neutrality issues.

One issue would be if we got a lot of accessibility companies, and not other strong ones, that might not help much.

(I would want to check with W3C Communications team, but I don't think it there would be any issues.)

Just a thought. Feel free to re-close the issue if you want.

**Comment by slhenry** [comment]
Here are [Testimonials Guidelines](https://www.w3.org/2004/12/testimonial_pr-guidelines.html)

**Comment by slhenry** [comment]
A possibility for business case study or at least testimonial https://www.barclayscorporate.com/insight-and-research/managing-your-business/making-your-business-accessible.html

**Comment by sharronrush** [comment]
Noted, added to Biz case wiki
