### ISSUE TITLE
Legal and policy benfits - Companies vs Countries

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-bcase#10]
In the paragraph: 

> ...Since its adoption by the UN General Assembly in December of 2006 and subsequent ratification by more than 150 nations, the Convention has been a powerful influence on the global legal and policy landscape related to web accessibility. *Companies* around the globe are implementing the Convention through laws and government policies. In many countries, such laws extend beyond government sites and services to to inlcude mandates for businesses that offer goods and services on the web.

Should "*Companies* around the globe..." be "*Countries* around the globe..."? 

Also, there's an extra "to" in "...beyond government sites and services to *to* include..."

**Comment by sharronrush** [comment]
changes made
