### ISSUE TITLE
Company Culture & Driving Innovation

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-bcase#100]
Possible additional reference about companies that have created a culture of accessibility: https://www.lflegal.com/2018/05/accessibility-culture/

... including this article with a historical perspective on creating a culture of accessibility and driving innovation at IBM: http://www-03.ibm.com/ibm/history/ibm100/us/en/icons/accessibleworkforce/

**Comment by sharronrush** [comment]
Thank you @carmacleod We have added these resources.
