### ISSUE TITLE
Acknowledge graphic artists

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#103]
Hi Sharron,

Any reason not to add the graphic artists' names to:
https://www.w3.org/WAI/business-case/acknowledgements/
?

An idea is to add a heading "Graphic Artists" above "Case Study Contributors"

(I'm happy to make that a pull request if you want to give me the names.)

**Comment by sharronrush** [comment]
Yes there is a reason, they are not supposed to be doing work outside their job and asked to be anonymous
