### ISSUE TITLE
Nav link not working & Breadcrumb wrong

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#109]
- [x] From https://www.w3.org/WAI/teach-advocate/ <br>In secondary nav, "Business Case" link gives 404<br><br>**_Note:_ I strongly prefer the simpler URI of https://www.w3.org/WAI/business-case/**

- [x] On https://www.w3.org/WAI/business-case/ <br>breadcrumb is wrong

**Comment by yatil** [comment]
Those two have been connected and should now be resolved :-)
