### ISSUE TITLE
Broken link in Barclay's case study

### ISSUE THREAD

**Issue by cmuncharaz** [w3c/wai-bcase#113]
File: index.md
Line: 213

A link to YouTube is supposed to show the Accessible Banking YouTube playlist, containing Barclay's animations. However, this link leads to a non available video.

**Comment by sharronrush** [comment]
Thanks for letting us know @cmuncharaz   I have repaired the link, it should be good to go. I appreciate your help!

**Comment by yatil** [comment]
I’ve uploaded the change.
