### ISSUE TITLE
Bracketed sentences

### ISSUE THREAD

**Issue by yatil** [w3c/wai-bcase#13]
I see some bracketed sentences, like

> [To avoid legal risk, accessibility is good business.]

> As we strive [to meet diversity and inclusion goals, companies find that accessibility is good business].

> [For companies that value innovation, accessibility is good business].

Are those “flagged for consideration” or do you want to have them emphasized in a special way? I think they are neat to tie together the theme of the page and I just want to understand why the brackets are there :-)

**Comment by sharronrush** [comment]
Thanks Eric, it's becasue I mean for that to be a link to the subpage related to that topic. Just hadn't gotten that far.
