### ISSUE TITLE
[ED] Accessibility is good for everyone

### ISSUE THREAD

**Issue by vavroom** [w3c/wai-bcase#16]
I really like the fact that it is pointed out that accessibility benefits many marginalized groups other than only people with disabilities as per: 

> While the term "accessibility" is focused on meeting the needs of people with disabilities, it is worth noting that accessible design also improves the user experience for...

I wonder if it wouldn't gain to be strengthened a bit and to point out that accessibility is good for EVERYONE.

This is not mission critical and might be better left to a future iteration so we're not delayed.

**Comment by sharronrush** [comment]
good point, updated and closed
