### ISSUE TITLE
[ED] Expansive ways

### ISSUE THREAD

**Issue by vavroom** [w3c/wai-bcase#17]
> But this is just the start in helping you think about the topic in creative and expansive ways

The term expansive is very close to expensive. I think there's a risk people might mis-read it and we should avoid giving the impression that accessibility costs a lot.

I suggest one of the following alternatives:

- Complete

- Holistic

- Comprehensive

**Comment by bakkenb** [comment]
+1

**Comment by sharronrush** [comment]
thanks, great point, I changed it to comprehensive
