### ISSUE TITLE
[ED][Format]

### ISSUE THREAD

**Issue by a11ycob** [w3c/wai-bcase#22]
Reflecting on Shadi's comments form last week's regarding the North American centric drivers, I am making the following recommendations [ED]:

**Under Minimize Legal Risk**

- Prepend the text "**In some countries**, legal risk is a strong driver for companies". I believe this simple addition acknowledges that this is not necessarily an international issue, but localized.
- Should we link to Robert's Law's and Policies resource from this section?

**Support Diversity and Inclusion**

- change this:

>  People all over the world are becoming more easily connected to one another. As more diverse people are connected, we all benefit.

 to 

>  More than ever, people are connected through technology. Increased connectivity promotes diversity, which is of tremendous benefit to society.

**Align with Global Web Standards**

An alternative approach to this sentence

> Businesses scramble to address growing markets, a broader audience, more browser diversity, and the expectation of increased speed while striving to also reduce the costs of maintaining or redesigning a web properties.

to

> With respect to developing and managing web properties, businesses face many challenges, including:  expanding markets, rapid changes in technology, rising user expectation, and increased pressure to maximize return on investment (ROI).

**Comment by slhenry** [comment]
+ change:

> * In the United States, courts are interpreting the Americans with Disabilities Act to be applicable to the web.
> * Globally, accessibility is mandated by the European Accessibility Act and similar laws are in place or in progress in Canada, Japan, Australia and elsewhere.

**Comment by sharronrush** [comment]
done
