### ISSUE TITLE
[!!][Content] Corporate Social Responsibility (CSR)

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#23]
I think we want that term and idea clear in this doc.

**Comment by slhenry** [comment]
fyi, here's what we said about it previously: https://www.w3.org/WAI/bcase/soc.html#responsible
(more wordy than we want to be in this revision. :-)

I particularly like the idea: Just as an accessible website can demonstrate CSR, an inaccessible website can undermine an organization's other CSR efforts.

**Comment by sharronrush** [comment]
add to overview - perhaps under diversity and inclusion, adding CSR in the overview page as both a positive and (if ignored) a negative

**Comment by slhenry** [comment]
Or, on the overview page, just the positive part. Then in the subpage, both aspects.

**Comment by slhenry** [comment]
Paraphrased direct quote from a large international corporation: We go above and beyond the minimum requirements. We need to avoid public complaints. It doesn't matter if we meet the minimum requirements and would "win" an argument. We need to avoid the negative publicity of a complaint.

It seems this is a primary issue for many organizations - public, private, etc.

**Comment by slhenry** [comment]
CSR is covered in the latest draft, so I'm closing this issue. Sharron or anyone else feel free to re-open if you want.
