### ISSUE TITLE
[ED][Legal CS] Case Study Question

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-bcase#24]
If we're talking about minimizing legal risk, should the case study reference a company that was potentially facing litigation but made the change to avoid it?   NPR made the change because of the FCC regulations, but maybe we should expand on the legal implications of those regulations.   I like the case study and think it really shows how you can increase your traffic to a website.  I just don't know if it belongs in the Minimizing Legal Risk section because I don't know if the tie is strong enough to the legal implications.

**Comment by sharronrush** [comment]
Kris Anne, these are great points. Do you know of an example case study of the kind you mention? If so I will gratefully include it. In the meantime however, this NPR/American Life example was a case where it seemed legal motivation provided unanticipated business benefits. If that point is not clear, I should make it more so.

**Comment by kakinney** [comment]
I don't know of any case studies off hand, but let me see if I can do some research and find any.   I am sure you've done so much research you've found it all though.  

If no other studies exist then yes, I'd like to see the language support that the legal motivation created these business benefits too.  Were there any news outlets that didn't abide by the FCC regulations and faced consequences?  Just wondering if that could be used to support this case too.  Something like, "unlike XYZ that didn't abide by the FCC regulations and faced legal actions brought forth by ABC, NPR took a proactive approach to transcribe their broadcasts."  I think if I recall, you only say the word legal once in the business case and that may not be enough to make the connection.

**Comment by sharronrush** [comment]
Pending the ID of a case study that fits your description, this is closed
