### ISSUE TITLE
[ED - Biz Case]

### ISSUE THREAD

**Issue by a11ycob** [w3c/wai-bcase#27]
small comment re: formatting.

Can we find another way other than centering content to highlight pull quotes? Tracking is challenging for some folks when irregular margins are introduced - particularly when using magnification software. Left-justification, perhaps with a small margin to differentiate it from other content, would be a much better option.

**Comment by a11ycob** [comment]
Spelling mistake: **Thr** International Institute of Sustainable Development

**Comment by sharronrush** [comment]
Thanks Chris, we will actually apply design to these pages so that the call out boxes are readable and accessible. Thanks for the reminder!

**Comment by a11ycob** [comment]
Spelling: A**n** significant demonstration of the risk of ignoring accessibility requirements was the 2008
