### ISSUE TITLE
Formatting of pull quotes

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-bcase#28]
From Chris (@a11ycob):
small comment re: formatting.
Can we find another way other than centering content to highlight pull quotes? Tracking is challenging for some folks when irregular margins are introduced - particularly when using magnification software. Left-justification, perhaps with a small margin to differentiate it from other content, would be a much better option.

**Comment by yatil** [comment]
That’s certainly what we want to do. I’m waiting for the illustrations and then we can develop a few styles of pull quotes that match the visual weight.

**Comment by yatil** [comment]
@slhenry We have a few different styles of pull quotes with different colors, see the Styleguide:

* Pull quote: https://w3c.github.io/wai-website-components/components/detail/blockquote--pullquote-right.html
* Color Alt 1: https://w3c.github.io/wai-website-components/components/detail/blockquote--pullquote-color-alt-1.html
* Color Alt 2: https://w3c.github.io/wai-website-components/components/detail/blockquote--pullquote-color-alt-2.html
* Color Alt 3: https://w3c.github.io/wai-website-components/components/detail/blockquote--pullquote-color-alt-3.html

Discussion of the pull quote formatting happened in this GitHub issues in the general wai design space: https://github.com/w3c/wai-website/issues/101

If there are general issues with design-related things, it’s best to open them in W3C/wai-website :-)

**Comment by slhenry** [comment]
I think it's good that we have different styles with different colors in the Design StyleGuide Components library -- so we can use what is best in a specific document/page.

I don't think that we want to have different color quotes in this one document. It looks to me like a mistake.

*possibly* have all quotes from others the same color, then the pull-outs from the text in black (which might help with https://github.com/w3c/wai-bcase/issues/45 )

**Comment by yatil** [comment]
@slhenry I did that. I think the black text helps a bit with #45, but we need another solution in the long run. Usually, I would use borders above and below the text and likely center it, but I don’t want it boxed in and centered is bad for accessibility. Maybe just using bold normal-size text would be an option?!

**Comment by slhenry** [comment]
cool.

/me comments in https://github.com/w3c/wai-bcase/issues/45
