### ISSUE TITLE
Resource

### ISSUE THREAD

**Issue by yatil** [w3c/wai-bcase#29]
I found this article that links to the (old) business case but also has a few more statistics that we might use or not:

https://medium.com/confrere/its-illegal-to-have-an-inaccessible-website-in-norway-and-that-s-good-news-for-all-of-us-b59a9e929d54

**Comment by slhenry** [comment]
Lots of good points, and non-English speaking country!

Sharron, what would you think of using some of this info in the narrative?

**Comment by sharronrush** [comment]
Yes, excellent, will do and will close once you both review and are satisfied.
