### ISSUE TITLE
Failure to address "Customer Satisfaction"

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-bcase#31]
Vicki @vmmiller noted that the narrative version does not sufficiently address how accessibility impacts customer satisfaction and that the bulleted alternative version does that and offers examples.

Customer satisfaction is referenced in the Barclay's case study and is implied in the section on Brand Enhancement but it is useful to know that the point is not made strongly and clearly enough.

My problem with the examples given in the bulleted alternative is that the claim of increased satisfaction is not really fully attributed to accessibility. The first article "Secret Benefits..." starts with a quote of improved customer satisfaction from Nielsen - but it is about about usability. The author spends the rest of the article making the connection, trying to build on the overlap - so seems a bit of a fudge. Usability is a measure of how easy it is to use a site, while accessibility relates to whether the site can be accessed specifically by people with disabilities. The two overlap and are often confused, but are not the same. The second one about Legal and General has also been subject to criticism from the community because a commitment to accessibility was part of an overall redesign and new approach so it was hard to tell where the improved customer experience data actually came from.  

Maybe in the market reach section, we include a text callout that is a simple as this:

"Designing inclusive software results in improved usability and customer satisfaction."
~ Microsoft's app developer guide

**Comment by yatil** [comment]
(follow up to #25)

**Comment by yatil** [comment]
(follow up to #25)

**Comment by slhenry** [comment]
(The second one is actually not Legal & General, it's:
> [Assessing The Value Of Accessible Technologies For Organizations](https://web.archive.org/web/20170710171528/https://mscorpmedia.azureedge.net/mscorpmedia/2016/07/Microsoft-TEI-Accessibility-Study_Edited_FINAL-v2.pdf) (Forrester-Microsoft 2016) — study found that implementing accessible web design minimizes the rate at which users abandon websites, which results in an estimated additional $2.4 million in annual revenue.
)

> "Designing inclusive software results in improved usability and customer satisfaction."
~ Microsoft's app developer guide

is a nice quote, and I support using it (although it's not backed up by data ;-)

**Comment by slhenry** [comment]
I think it would be good to clearly communicate that points Vicki refers to:

> Accessibility can positively impact how satisfied users are with your website — including users with disabilities and without disabilities.

> Conversely, accessibility problems will likely negatively impact user satisfaction for people with disabilities. And also for people without disabilities in various situations such as using their phone in bright sunlight and others in Accessibility Benefits All Users above.

I also think it would be good to include the information that [Accessibility Benefits all Users](https://w3c.github.io/wai-bcase/alt/#allusers). I know you want to quote other people and not just us; however, these seem obviously supported.

**Comment by slhenry** [comment]
I just now read "Added benefit: as accessibility features are included, overall customer satisfaction improves." I do think that would need support -- whether it's like https://w3c.github.io/wai-bcase/alt/#allusers or other.

**Comment by sharronrush** [comment]
Under Accessibility is Good Business, added the following:

Among multiple benefits cited above is the recognition of improved customer experience. For customers with diabilities, that improvement is essential for equal access. Also worth noting are the ways in which accessibility is useful for broader audiences in various scenarios. For example, web accessibility also benefits:
* people using mobile phones, smart watches, smart TVs, and other devices with small screens, different input modes, etc.,
* older people with changing abilities due to ageing
* people with “temporary disabilities” such as a broken arm or lost glasses
* challenging situations like bright, glaring sunlight or in noisy environments where audio can't be heard
* those with a slow Internet connection, or who have limited or expensive bandwidth, which is common in some rural areas and geographical regions
