### ISSUE TITLE
Failure to address "Decrease expenses"

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-bcase#33]
I have more trouble with this one @vmmiller because this again is an example of something that we claim (one of the links is to the old business case) without real bottom line validation. We speculate that costs decrease, but where are the numbers that say:  "This company implemented accessibility and their costs for translation or alternative materials or server costs or maintenance went down?" and that the decreased costs more than made up for the additional amount they may have spent learning about,  training, testing, and sustaining accessibility.

I would so love to include an example that really shows accessibility decreasing expenses, but neither of these do that in my opinion.  I will keep looking.

**Comment by slhenry** [comment]
Hi Sharron. I appreciate your wanting to get validation of claims for this version of the business case -- that is, I support you in it.

The first link is:
> [Legal & General Group Case Study](https://www.w3.org/WAI/bcase/legal-and-general-case-study) — cut maintenance costs by two thirds.

"It has cut maintenance costs by two thirds" is a direct quote from them. The linked case study includes "Reduction in maintenance costs by 66%" and "100% return on investment (ROI) in 12 months"

I'm missing how that doesn't provide validation of the claim for decrease expenses/costs.

**Comment by slhenry** [comment]
Comment on a separate point:
>  ...that the decreased costs more than made up for the additional amount they may have spent learning about, training, testing, and sustaining accessibility.

Overall, I think this is a point that we should address internally at least. I think that in most (probably all) cases, the decrease costs will **not** make up for the additional amounts spent on accessibility. Does that mean "decrease costs"  is not at all a factor in the business case?

I think when we are presenting several factors that influence the business case, then "decrease costs" is a a legitimate, albeit minor, point. We just need to present it not as the decreased costs alone will provide ROI, but that decreased costs is a potential financial benefit.

Does that make sense?

First, I would like to get shared understanding on this issue -- that something can benefit the organization and be a factor in the business case, even though it **alone** does not make the case.
(And that we have specific examples of how accessibility can decrease costs.)

Then, we may decide that this point is not strong enough to take up space in the business case -- or we may find a way to weave it in effectively.

**Comment by yatil** [comment]
(follow up to #25)

**Comment by sharronrush** [comment]
> First, I would like to get shared understanding on this issue -- that something can benefit the organization and be a factor in the business case, even though it alone does not make the case.

Yes, I entirely agree that shared understanding is needed. For example, I have sometimes heard, when I give the Legal and General example, that the benefits cannot be attributed to accessibility alone. They had several objectives in that redesign - valid code, updated structure for SEO, usability factors around findability etc. So the most I found I was able to say with confidence was that "accessibility when integrated into a design approach contributes to improved usability, findability, SEO, blah blah blah."

It would be so great to get clarity. I think it doubtful that we will ever find a project where accessibility was the only improvement to a site design. A good example may be to avoid remediation costs, I will try to work on that angle and continue to look for clear examples of direct cost reductions.

**Comment by slhenry** [comment]
Yup, I also agree that many accessibility improvements go along with other improvements, and therefore you often cannot say that the accessibility improvements only directly resulted in XYZ benefits -- and that is especially the situation with the Legal & General case study.

I *think*, but don't know, that the L & G "Reduction in maintenance costs by 66%" was directly related to accessibility only. (whereas the SEO and other ROI benefits were likely due to other improvements as well)

---

Separate from that or other specific case study, do you agree with the point that "something can benefit the organization and be a factor in the business case, even though it alone does not make the case"?

**Comment by yatil** [comment]
We talked a little bit in the EO planning meeting, and my take (that I note here so I don’t forget 😂) is:

> In redesigns that included accessibility and other best practices, a reduction of maintenance, service and traffic cost was observed.

Or something along the lines. Basically portraying accessibility as one of the best practices that help your website.

**Comment by sharronrush** [comment]
In the Market Reach section, just below the bullets, added this paragraph

> A Forrester study commissioned by Microsoft concluded that accessibility can contribute to cost savings when it is integrated into existing and ongoing development cycles. (16) Technology updates and redesigns that include accessibility along with other best practices demonstrate reduced maintenance, service, and traffic cost. And, according to Microsoft, as accessibility features are included, overall customer satisfaction improves. (followed by the quote from MS designer tools page)

also linked to Forrester study
