### ISSUE TITLE
Peripheral resources needed

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-bcase#34]
@slhenry said:
A brainstorm idea:
    "Exploring the Business Case" is the story edition with the current approach and tone (including footnotes -- I'll comment on that separately)
    "Business Case Summary" (or "At-a-Glance" to match other WAI resources) - has just the headings and short paragraph from the **[bullet edition](https://w3c.github.io/wai-bcase/alt/)** -- no expand-collapse examples.
    "Resources for the Business Case" is a separate page that both point to.
    Template (if that pans out)

**Comment by yatil** [comment]
I find that confusing.

**Comment by bakkenb** [comment]
Would like to stay focused on current on page resource now and get it published. Then we can solicit and gather feedback for a period of time to find out what the accessibility community is needing/looking for in addition to this one page resource. At that time we can revisit some of these other add-ons when we have determined the demand for them.

**Comment by sharronrush** [comment]
Closed with an action to revisit in March after doing user testing and gathering community feedback.
