### ISSUE TITLE
[!!] International perspective

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#35]
I'm concerned some readers will find this is too US and English-language country focused. It would be good to get examples and references from other regions.

Once we have a draft that we are comfortable circulating (e.g., named organizations are on record that they are comfortable with what we've said about them and their products), then I think we need do another push for getting other examples and references. I can help with some direct inquiries.

**Comment by slhenry** [comment]
Found an example that makes it seem US focused:
> In addition, the many legal precedents in the United States continue to accumulate and the landscape is changing in favor of equal access.

**Comment by sharronrush** [comment]
Yes it is true that legal liability is more US focused because that is where litigation occurs. @yatil has offered to find international examples but they are few and far between. So the reality seems to be that legal risk has been mostly a US-centic issue. Welcome other examples to broaden the claim. looks like Norway has jumped in https://medium.com/confrere/its-illegal-to-have-an-inaccessible-website-in-norway-and-that-s-good-news-for-all-of-us-b59a9e929d54 so I will look for a way to work that in.

**Comment by yatil** [comment]
I think we can start US-centric and publish and then ask people for other examples. Here’s my long promised Austrian one:

> In Austria, almost all websites fall under the customer protection regulation and must be accessible since 2006. Customers that are discriminated against can take legal action. In contrast to other countries, both parties meet in mediation before it is possible to go to court. 

I hope that’s the detail we want to go into, the best example is probably [this chain of mediation and then suing with the public TV station ORF over captioning their online videos](https://www.bizeps.or.at/schlichtungen/untertitelung-der-online-videos-fehlt/). The list here has 162 examples, which also include violations of the building code and captioning of DVDs and so on: https://www.bizeps.or.at/schlichtungen/

**Comment by sharronrush** [comment]
Reference from @yatil : https://medium.com/confrere/its-illegal-to-have-an-inaccessible-website-in-norway-and-that-s-good-news-for-all-of-us-b59a9e929d54

**Comment by slhenry** [comment]
Cool. As I said before, I think that image with other currencies is a subtle but strong help (for people who can see it)

Did you connect with Vivienne?
> SLH: Vivienne recently did work in Qatar. Maybe contact her to see if they have info to share -- not necessarily for legal section, but other sections on what motivates them to address accessibility and invest all that they have in it<br>&mdash; [mins](https://www.w3.org/2018/08/16-eo-minutes.html#item02)

Also, Eric had another idea in e-mail -- I'll try to dig it up.

I would like to leave this open and:
> Once we have a draft that we are comfortable circulating (e.g., named organizations are on record that they are comfortable with what we've said about them and their products), then I think we need do another push for getting other examples and references. I can help with some direct inquiries.

**Comment by bakkenb** [comment]
I think good to check with Vivienne as we said before on the meeting.

I don't want to hold up the publishing though by doing another push to be more examples. I think we need to circulate with companies named and make any adjustments requested (or work for a happy solution) and then publish. Then we can do more of a push at that time, or ask in the bottom of the document for others who would like to contribute stories of success. 

I don't want to do anything that will hold this up more than needed. Checking with Vivienne and the companies is enough.

**Comment by sharronrush** [comment]
No response from Vivienne, incorporated other international suggestions from Eric, removed detailed US history. Closing the issue, feel free to re-open if not satisfied.
