### ISSUE TITLE
CRPD & legal risk

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#37]
> Legal risk became even clearer with the adoption in 2006 of the United Nations Convention on the Rights of People with Disabilities (CRPD).

Certainly the civil rights issue because clearer. Is it also true that the legal risk became clearer? I don't know of legal issues around CRPD enforcement.

maybe @nitedog , @brewerj , or others know?

**Comment by yatil** [comment]
„Legal risk became even clearer with the adoption of the United Nations Convention on the Rights of People with Disabilities (CRPD) and its adoption in the laws and policies of countries around the world.“
