### ISSUE TITLE
Disability related wording

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#38]
I would be more comfortable changing the wording quoted below - ideas provided (and maybe you can find an even smoother way). Happy to discuss as useful.

"for temporary disabling conditions" -> for situational limitations
"the disabled community" -> people with disabilities

disability "accommodations" &mdash; I realize "accommodations" is a common term in many environments. Yet I think it can be taken negatively by many readers, especially non-English speakers -- as we have to do special, limiting things for disability. A definition includes "a settlement or compromise".

ideas for tweaks:
* "originally meant as accommodations for disability" -> originally developed to meet the needs of people with disabilities
* "In physical environments everyone takes advantage of lower curbs, automatic door openers, ramps, and other disability accommodations. On the web, such accommodations can be used by everyone, too." -> "In physical environments everyone takes advantage of lower curbs, automatic door openers, ramps, and other designs to meet the needs of people with disabilities. On the web, such designs can be used by everyone, too."

I think it's fine to leave "accommodation" in the Winn Dixie case study since that is specifically addressing ADA which uses that wording.

**Comment by yatil** [comment]
OK with replacing accommodations with simpler wording :-) 

> "for temporary disabling conditions" -> for situational limitations

I wondered about that, but I feel that the former is easier to understand for people who have no knowledge about the topic at all.

**Comment by slhenry** [comment]
RE:
> I wondered about that, but I feel that the former is easier to understand for people who have no knowledge about the topic at all.

I'm uncomfortable with "temporary disabling conditions", and I think some others would be as well. I agree there could be better other wording. I can think more about it if needed.

Seeing it in context could help with wording ideas:
> Addressing disability barriers anticipates solutions for temporary disabling conditions. For example: noisy or too bright environments.

**Comment by yatil** [comment]
Brainstorm:

> Addressing disability barriers anticipates solutions where the situation limits a user’s (sensory?) abilities temporarily for example in noisy or too bright environments.

**Comment by bakkenb** [comment]
I agree with the need for wording changes that @slhenry pointed out above. 
- I like the change to "people with disabilities"
- I like the change moving away from using the word accommodations (in this instance)

I agree with @yatil that "situational limitations" is difficult to understand and I like the brainstorm wording that he has introduced.

**Comment by nrhsinclair** [comment]
Both 
people with “temporary disabilities” such as a broken arm or lost glasses
and
people with “situational limitations” such as in bright sunlight or in an environment where they cannot listen to audio
are used on this page https://www.w3.org/WAI/fundamentals/accessibility-intro/
Suggest using both, "people with/ or experiencing temporary disabilities" and "situational limitations" since both can apply in different situations:

**Comment by sharronrush** [comment]
Changes made to remove accommodation, temporarily disabling, disability community, etc
