### ISSUE TITLE
Conclusion? [ED - Biz Case]

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-bcase#39]
The conclusion ends rather abruptly and has the word Please just hanging there at the end.  Will the Conclusion be made more robust like the summary was?    I know the original summary was short too.

**Comment by sharronrush** [comment]
rewritten as follows:
Public use of the Internet is more than 25 years old. The web is no longer a novelty but an integrated, critical tool of modern life. Smart businesses understand the need for equal access by all people as they integrate accessible design into their development and procurement processes. While the legal risks of ignoring accessibility are significant, the benefits have also been demonstrated by leaders like Apple, Barclay’s, NPR, IBM, Microsoft and hundreds more. Business leaders and the advocates who influence them can have tremendous social impact and healthy ROI as they follow a roadmap that leads to equal access. More than one billion people with disabilities in the world are eager to enagage with you as customers, clients, partners, employees, and full participants. By developing a long term commitment to accessiblity and using WAI resources to develop policy and implement strategy to bring that commitment to life, your business will reach this market and is likely to thrive in unexpected and self-sustaining ways.

**Comment by sharronrush** [comment]
Closed following discussion at 24 Aug telecon
