### ISSUE TITLE
[ED - Biz Case] imagery

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#42]
In response to [survey question](https://www.w3.org/2002/09/wbs/35532/24August2018/results#xq9):

I **much prefer version 2 style** -- it's **stronger** and more refined looking. (also, the colors match the site better)

Minimize legal risk image:
- I think not have a seal/ribbon since it conveys a seal-of-approval that we don't provide.
- I prefer not to have "LEVEL AA".
- Instead, how about use a _simplified_ version of the conformance logos <https://www.w3.org/WAI/standards-guidelines/wcag/conformance-logos/#wcag-21-logos> with just:
	**[ W3C | WCAG ]**     _(without WAI or 2.1 or  AA)_
- (minor: Think can simplify image by removing the bowls. and simplifying the base... actually the base might be better as a simple triangle.)

Rocket, Robot:
- Much prefer robot over rocket.
- Might want to change the robot's hand positions ;-)

Speaking bubbles:
- Remove underline (to avoid linkable affordance).
- I didn't get that they were supposed to be what other people were saying about the organization. Possibly add person saying them, or "customer" or something -- but probably not worth the additional image complexity. No big deal, anyway.

**Comment by bakkenb** [comment]
**Who Needs a Business Case:**
- Like the briefcase better than the chart
- Would remove arrow image from briefcase. Seems out of place and the header it is matched with really doesn't get into the concept of improvement or "increase" yet.

**Drive Innovation:** 
- Like the robot better than the rocket.
- Robot in the rocket looks scared. Don't want that.
- Make robot icon slightly smaller, but not much, to match other icon sizes more.

**Enhance Your Branch:**
- Like the call-out bubbles better than the DNA helix.
- Agree with Shawn to remove the underlines
- Change "Diverse" to "Inclusive"
- Add a third bubble, maybe "Flexible" or "Functional" or "Always works"

**Increase Market Reach:**
- I like the shopping cart/coins better than the increasing chart.
- Could even move the "$" to the back and make it the smallest of the currency types
- Could add Bitcoin (just kidding - LOL)

**Minimize Legal Risk:**
- Agree with Shawn about removing the ribbon. If something is needed, then maybe a check-mark.
- Agree also about removing "AA". WCAG is enough.
- I like that the scale is balanced. Seems more like "The decision is yours, roll the dice to take a chance, or implement WCAG to remove risk."
- Scale design itself could still use some more work to help it look a little more like a scale. ([example 1](https://openclipart.org/detail/305081/flyweight), [example 2](http://clipart-library.com/clipart/pcoabyRqi.htm)) - These are examples and could use the same style that is used now, but a bit more like these in form.

**Comment by yatil** [comment]
I like **version 2** better, apart from the scale. I think the scale has a different look and doesn’t look as strong/bold as the other icons. Unsure if it lends itself to a stronger look. (Brainstorming yielded no real good ideas: A window with bars, a hammer (not used in courts outside of the US or UK, but recognizable, because cultural imperialism 😉), maybe just a § sign and the WCAG certificate?)

**Comment by vmmiller** [comment]
I definitely prefer version 2 but for one image:   the scale under Minimize Legal Risk.

**Comment by nrhsinclair** [comment]
I like most of version 2 better, except prefer scale on version 1, also prefer the graph with arrow for increase market reach rather than the shopping cart.

**Comment by sharronrush** [comment]
@yatil, please make the following changes (I am still waiting for banner imagery and a scale substitute from the volunteer). These will still not be final but more of the ones people want will be in place
![brief-case](https://user-images.githubusercontent.com/6991827/45189554-2f1ce600-b1ff-11e8-9623-488aa4104bb1.png)
- Use the attachment for Who Needs a Business Case (brief case with the arrow removed)
- For innovation, replace with the robot from the alt version
- For brand enhancement, replace with conversation bubbles (she is working on the suggested changes so use the alt version for now)
- For market reach, replace with shopping cart
- For legal, leave the scale in place, she is working on an entirely new image.

**Comment by yatil** [comment]
@sharronrush done!

**Comment by sharronrush** [comment]
I think all the image issues are now resolved, thanks all!

**Comment by slhenry** [comment]
I'm not going to re-open the issue, because it is so teeny-tiny, yet I do want to note it 'cause it keeps catching my attention: "Responsible" is crammed into it's dialog bubble -- would be better to have some spaces around it (like the others do).

**Comment by yatil** [comment]
@slhenry I will make sure to do that tomorrow. (It is SVGs, so it should not be hard :-D)

**Comment by yatil** [comment]
@slhenry Done.
