### ISSUE TITLE
Quotes without attribution - possible oversight

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-bcase#45]
There are two quotes with no reference to the origin.  Oversight or deliberate?

**Comment by sharronrush** [comment]
Deliberate, they are just quotes pulled out from the text, not quotes from others. Thanks for asking :)

**Comment by slhenry** [comment]
I had the same question.

They aren't elsewhere in the document like a typical callout in an article, so it's impossible to know that.

I think at the very least they need to be formatted differently -- without any quote marks -- so it is very clear that they are not un-referenced quotes from others.

**Comment by yatil** [comment]
- [ ] No quote marks
- [ ] I guess special formatting for a paragraph instead of a blockquote

I’ll see that I get to it next week, but I’m heavily traveling…

**Comment by yatil** [comment]
I don’t feel confident to just remove the quote marks. It might look like a weird heading or something…

**Comment by slhenry** [comment]
@yatil, Then we need another solution.
I agree with the original comment that they look like referenced quotes from others, that are missing attribution.

I think removing the quotes will be OK and sufficiently differentiate them:
* referenced quotes are colored, have quote marks, are italic, are indented
* pull-outs from text are black, don't have quote marks, are italic, are indented
* headings are colored, some have pale underline, not italic, not indented

It it would be good to see it in a draft and get other perspectives.

**Comment by slhenry** [comment]
From https://github.com/w3c/wai-bcase/issues/28#issuecomment-424788163

> Maybe just using bold normal-size text would be an option?!

I support that!

**Comment by yatil** [comment]
Do they have to be larger text? Would just a bold paragraph not be sufficient? I try to keep it simple, and without the quote mark and just the indentation, it looks like something was forgotten, like a broken quote (but still a quote).

**Comment by yatil** [comment]
oops, cross-posted :-) Let’s do it for now.

**Comment by yatil** [comment]
Done in https://github.com/w3c/wai-bcase/commit/d3707520f0ba8bf4c7618535e6cdc98b6e3201aa – I’m happy to look at it again, but I think removing the confusion is the important step here :-D

**Comment by sharronrush** [comment]
OK to close @yatil and @slhenry ?

**Comment by slhenry** [comment]
OK by me.
