### ISSUE TITLE
Minor suggestion to reverse the order of two sentences plus a small typo

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-bcase#46]
This paragraph tells a very good story.  I'd suggest simply reversing the order of two sentences to allow for a more logical flow of information.

Current:
A compelling example of how this wroks comes from the early 2000’s as the online world increasingly adopted mobile devices to browse the web. Imagine the delight of those who were already committed to and had designed for accessibility. Accessible, standards-compliant web sites were in many cases more mobile-ready as interaction options were already baked in. This realization led to the responsive-design trend that has accessibility at its core.

Suggestion (changes in bold, plus an exclamation mark at the end of the second last sentence):
A compelling example of how this w**or**ks comes from the early 2000’s as the online world increasingly adopted mobile devices to browse the web. **Those web sites which were a**ccessible and standards-compliant were in many cases more mobile-ready as interaction options were already baked in.  Imagine the delight of those who were already committed to and had designed for accessibility!  This realization led to the responsive-design trend that has accessibility at its core.

Note :  it's just a suggestion and no worries if it is too late to change.
Typo:  first sentence "wroks" to "works"

**Comment by sharronrush** [comment]
Done, thank you
