### ISSUE TITLE
[ED] succinct strong statement for accessibility fuels innovation for all

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#57]
This really stood out to me from https://www.fastcompany.com/3060090/how-designing-for-the-disabled-is-giving-google-an-edge

> **The robots of the future might be able to “see” because of the accessibility work done in computer vision for blind people today.**

Seems like it succinctly and clearly illustrates the accessibility-fuels-innovation-for-all point.

... although I guess this is future speculative instead of past proof. :-/

Anyway, feel free to close this issue. I just wanted to point it out in case you thought it might fit in.

**Comment by slhenry** [comment]
/me just realized that that quote would go well with the robot image!!! :-)

**Comment by sharronrush** [comment]
Included in the bulleted list next to the robot

**Comment by slhenry** [comment]
Need to add quote marks and reference (so not plagiarism).

**Comment by sharronrush** [comment]
I will change the wording instead of referencing it twice
