### ISSUE TITLE
Links to "Factors" pages within each corresponding "benefits" section?

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-bcase#6]
On the Accessibility is Good Business page, we have sections for:

- Social Benefits
- Technical Benefits
- Financial Benefits
- Legal and policy benefits (sic)

and we also have corresponding pages in the left nav with links of:

- Social Factors
- Technical Factors
- Financial Factors
- Legal and Policy Factors

**Question:** Should we consider adding a simple callout or sentence to link to the Factors pages from each of the benefits sections on this page?

**Comment by sharronrush** [comment]
Yes, the "factors" titles will change to benefits as the resource is developed.

**Comment by sharronrush** [comment]
closed for now to reconsider the entire structure
