### ISSUE TITLE
association with UNCRPD

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#60]
From https://w3c.github.io/wai-bcase/teach-advocate/business-case/#minimize-legal-risk

>Legal risk became even clearer with the adoption of the United Nations Convention on the Rights of People with Disabilities (CRPD) and its adoption in the laws and policies of countries around the world.
>* CRPD ratified by more than 140 countries by 2016.
>* It is a comprehensive human rights document that includes direct reference to the rights of all people to have equal access to communications technology.
>* Number of legal actions in US increase and courts increasingly decide in favor of equal access19
>* The strategy of Structured Negotiation proved effective in helping companies integrate accessibility while avoiding litigation. 20
>* European Commission adopts European Accessibility Act, requiring ATMs and banking services, PCs, telephones and TV equipment, telephony and audiovisual services, transport, e-books and e-commerce meet accessibility requirements.

One could read above as the first sentence introducing CRPD and the bullets expounding on CRPD. Indeed the first two bullets apply to CRPD, and the second bullet is dependent on the sentence or bullet above.

However, the latter 3 bullets don't apply to CRPD.

**Comment by sharronrush** [comment]
OK re-written as follows. If OK,  please close. 

The 2001 decision in the Sydney Olympics suit18 raised awareness of the need to address accessibility in the emerging practice of web communication. Legal risk has increased with the adoption of clearer laws and policies in countries all over the world.

- - The  Convention on the Rights of People with Disabilities (CRPD) is a comprehensive human rights document that includes direct reference to the rights of all people to have equal access to communications technology. Passed by the General Assembly of the United nations, it was ratified by more than 140 countries by 2016.

- - The  European Commission adopted the European Accessibility Act, requiring ATMs and banking services, PCs, telephones and TV equipment, telephony and audiovisual services, transport, e-books and e-commerce meet accessibility requirements.

- In the US, the number of legal actions continues to rise and courts increasingly decide in favor of equal access19, often citing the Americans with Disabilities Act (ADA.) A strategy of Structured Negotiation is another way that companies meet accessibility requirements within a legal structure while avoiding litigation. 20

Change is occurred incrementally and steadily. Legislation continues to pass...

**Comment by slhenry** [comment]
Yes that rewrite takes care of this issue.
