### ISSUE TITLE
[!! - Biz Case] Missing link for reference under Increase Market Reach

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-bcase#61]
I think this bullet needs a reference see [1415] 

- "In countries with life expectancies over 70 years of age, people spend 11.5 per cent of their life span living with disability.**[^1415]**"

**Comment by sharronrush** [comment]
Thanks @lakeen , when I added number 15, I made a typo in the link. It should be fixed now, take a look and if it seems OK to you, please close this issue. Also, can you confirm that these citations actually validate the claim made in the article? Thanks!

**Comment by lakeen** [comment]
Thanks Sharron.  I can confirm that the citations validate the claim made in the article. I spent a few hours yesterday reading through 12-23.
