### ISSUE TITLE
[ED - Biz Case]

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-bcase#63]
The bullet points under the NPR Case Study could possibly be reworded to flow a little better:

Currently:
- search traffic increased 6.86%,
- better comprehension for visitors who use English as a second language,
- visitors were able to use transcripts in noisy or sound-sensitive environments,
- ability to more easily translate, and
- ability to search text to reference a specific section of audio.

Suggested changes (in bold):
- search traffic increased **by** 6.86%,
- **there was** better comprehension for visitors with English as a second language,
- **transcripts proved to be very useful to visitors** in noisy or sound-sensitive environments,
- **translations were easier to do and outreach increased**
- **referencing a specific section of the audio was enabled through text search**

**Comment by sharronrush** [comment]
done, thanks again!
