### ISSUE TITLE
[ED - Biz Case]

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-bcase#65]
Case Study NPR:

Currently:
The study conducted over more than one year, used Google analytics to capture the following data:
- visitor engagement increased 7.23%,
- unique visitors increased 4.18%, and
- new inbound links to transcript accounted for increase of 3.89%

Read more detail and the full report of the This American Life Case Study and how it was conducted.

Suggested changes (in bold):
The study, **which was** conducted over more than one year, used Google analytics to **track visitors**.  The following positive results were noted:
- visitor engagement increased **by** 7.23%
- unique visitors increased **by** 4.18% and
- new inbound links to transcripts accounted for **an** increase **of** 3.89%

Read more **in** detail and the full report of the This American Life Case Study and how it was conducted.

**Comment by bakkenb** [comment]
+1

**Comment by sharronrush** [comment]
done, thanks Vicki.
