### ISSUE TITLE
Language in "Who needs a business case"

### ISSUE THREAD

**Issue by RachelComerford** [w3c/wai-bcase#66]
This is a small change but this line:

"For example, government businesses may be more committed to the legal and equity aspects while commercial businesses care more about the brand enhancement provided by an integrated accessibility program."

Implies that commercial businesses only care about how they look to others. I would make this tiny change (insert another May):

"For example, government businesses may be more committed to the legal and equity aspects while commercial businesses may care more about the brand enhancement provided by an integrated accessibility program."

**Comment by sharronrush** [comment]
Done. Thanks Rachel!
