### ISSUE TITLE
spellin

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-bcase#73]
The link between the website and Winn-Dixie Stores was a **circumatance** that made Title III of the ADA, applicable to “Public Accommodations,” relevant in this situation.

should be "circumstance" 

and 

Website must **be be** made accessible to “individuals with disabilities who use computers, laptops, tablets, and smartphones.”

remove one "be"

**Comment by sharronrush** [comment]
Thanks @lakeen corrected and closed the issue
