### ISSUE TITLE
[ED - Biz Case]

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-bcase#82]
Reference #2 isn't linked to the actual resource.  I know it's not freely available, but people still may want to get it since it could help their case.  

I found the link to the [MIT website where the resource is from.](https://mitpress.mit.edu/books/design-meets-disability)

**Comment by sharronrush** [comment]
It is a book, not a live link. The book is call "Design Meets Disability" and is properly referenced for a print publication rather than an online reference.
