### ISSUE TITLE
[ED - Biz Case]

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-bcase#83]
In a few places "business case" is referenced and others its "Business case".  Is there a reason for the capitalization sometimes?

**Comment by sharronrush** [comment]
Yes it should be business case unless it leads the sentence. Please point out where you found those @kakinney so they can be corrected.

**Comment by kakinney** [comment]
Who Needs a Business Case? 2nd paragraph -
Determining which of the many benefits of web accessibility are most relevant in your business environment will help you build the most compelling Business case for your situation. 

Minimizing Legal Risk - 1st paragraph -
Consideration of the cost and risk of inaction is a critical aspect of any Business case.

**Comment by sharronrush** [comment]
done, thanks @kakinney
