### ISSUE TITLE
[!!] Summary 

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-bcase#84]
I removed this intro to the summary at the request of a few readers. However, I am not happy with the result because this opening argument that has now been deleted is a definitive statement that sets up all the rest.  Too often people think that to make a convincing business case, you must show a definitive ROI.  That is not, in fact, the purpose of a business case. To say that everyone knows what a business case does and so there is no need to repeat it is actually incorrect. There is wide spread misunderstanding about a truly effective business case and we should make that clear from the start.  

A business case is a rationale for initiating a project or task. Whether formal and highly structured or informal and brief, a good business case will articulate both tangible and intangible benefits to the business for dedicating resources to a project. To be effective, consideration will be given to cost, benefit, and resource gap analysis. The business case also presents the cost and risk of inaction.

**Comment by yatil** [comment]
If you strongly disagree, then don’t merge it. I agree that it is important for readers to understand what a business case is, but there is a whole section that explains it that is easy to find. Feel free to re-add what you think is needed. It was marked editor’s discretion for a reason. :-)

Maybe a brief sentence is enough, from my point of view the summary explained more what a business case is than giving me a summary of why I should care about reading the article, the balance felt off. It is totally possible that my changes overshot in the other direction.
