### ISSUE TITLE
Proposed edit

### ISSUE THREAD

**Issue by a11ycob** [w3c/wai-bcase#86]
current: Business performance and current research indicate that accessibility integration can help companies realize these benefits:

Suggested: Research indicates that integrating accessibility into businesses can help companies realize these benefits:

**Comment by a11ycob** [comment]
current: Organizations and enterprises of all kinds require a business case for the pursuit of a policy or course of action. 
proposed: A business case is a necessary tool for organizations when planning for various initiatives.

**Comment by a11ycob** [comment]
current: Determining which of the many benefits of web accessibility are most relevant in your business environment will help you build the most compelling Business case for your situation.

proposed: To create a compelling business case, it is important to highlight the most impactful accessibility benefits. Doing so will inspire confidence among leaders and decision makers that continued investment in accessibility is good for your business.

**Comment by a11ycob** [comment]
current: A research study of Fortune 100 companies indicates that disability inclusion as part of an overall diversity strategy is common practice among high performing businesses

proposed: A research study of Fortune 100 companies indicates that disability and inclusion, as part of an overall diversity strategy, is common practice among high performing businesses

**Comment by a11ycob** [comment]
current: Accessible design thinking creates flexible interaction options useful beyond people with disabilities.

comment: can we flush this out a bit more? Not sure this bullet point is clear

**Comment by a11ycob** [comment]
current: In physical environments, everyone takes advantage of lower curbs, automatic door openers, ramps, and other features provided for disability access. 

proposed: In physical environments, everyone benefits from curb cuts, automatic door openers, ramps, and other features provided for disability access.

**Comment by a11ycob** [comment]
current: Apple engineers have .... **As well,** the company anticipates market direction by integrating disability needs into product development. 

proposed: In addition, the company...

**Comment by a11ycob** [comment]
current:  Iterating over several years behind the scenes, the company invested the resources to develop the voice technology that led to VoiceOver,

proposed:  Over several years, the company invested tremendous resources to develop the voice technology that led to VoiceOver,

**Comment by sharronrush** [comment]
I have integrated the first several edits edits, thank you @a11ycob ! The ones below need more discussion:
current: Accessible design thinking creates flexible interaction options useful beyond people with disabilities. / comment: can we flush this out a bit more? Not sure this bullet point is clear 
SR: Please suggest specific word changes as you did before, that is most helpful. Thanks

Your suggestion to change "lower curbs" to "curbcuts" would reverse an edit suggested becasue "curbcuts" was considered jargon for translation, not used outside north america.

The ones from Apple were written by them and so we cannot edit, unfortunately. 

If you feel strongly aobut any of these, please re-open the issue and we will bring it to a meeting.

**Comment by a11ycob** [comment]
Understood on all of your points. Makes sense.

With regards to the bullet point - I didn't suggest an edit because I wasn't sure I understood the essence of it.
