### ISSUE TITLE
[ED - Biz Case]

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/wai-bcase#91]
Because this is the first bullet point under the first benefit, I think it would be better if it was more inclusive and did not immediately move "beyond people with disabilities"
Under Drive Innovation:
"Accessible design thinking creates flexible interaction options useful beyond people with disabilities."

perhaps more along the lines:
Accessible design thinking creates flexible interaction options useful for people with and without disabilities.

(also "beyond" is used in the second bullet point as well).

**Comment by bakkenb** [comment]
+1 [ED]

**Comment by sharronrush** [comment]
Done, thanks!
