### ISSUE TITLE
[ED - Biz Case]Increase Market Reach

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/wai-bcase#92]
Should the subheading "Increase Market Reach" be placed after the last paragraph about Barclays and before the information about Microsoft begins? I was a little confused to see Microsoft again after the list of statistics. Due to the new heading, Increase Market Reach, I thought the microsoft part had ended.

**Comment by bakkenb** [comment]
I see what you mean, but I think that the Microsoft paragraph is still supporting the "Enhance Your Brand" topic and is in the correct spot (if I am understanding your comment correctly Norah - I may not be and be wrong).

**Comment by sharronrush** [comment]
Yes, the Microsoft example is meant to be another case where respect for the brand was improved by a genuine commitment to accessibility.
