### ISSUE TITLE
[ED - Biz Case] minor rewording auto-captioning

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/wai-bcase#93]
Suggest possible minor rewording:

"auto-captioning for the deaf using machine learning was problematic at first and as it has been steadily improving, is now being turned to broader applications" to

auto-captioning for the deaf using machine learning, though problematic at first, now as it has been steadily improving, has broader applications

**Comment by bakkenb** [comment]
+1
Would tweak Norah's suggestion a bit more to make it flow better.

"auto-captioning for the deaf using machine learning, though problematic at first, has been steadily improving, and now has broader applications"

**Comment by sharronrush** [comment]
The edit makes it significantly longer but I beleive addresses all concerns.  The bullet now says:
auto-captioning for the deaf using machine learning has been problematic for the main target population of deaf users and many feel it is still inadequate to meet that need. However, work continues and machine learning itself is steadily improving and has found broader applications die to this effort.
